print("\033c")
print("Welcome to the world of programming")
print(15 + 30)
print("15" + "45")
print("My name is  Maimuna and I am ", 10+2 , "years old")
print(f"My name is Maimuna and I am {10+2} years old")